.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation_improvements.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/maintenance.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-title.yaml

- Add templates for filing issues and submitting pull requests. These are taken from https://github.com/awslabs/aws-lambda-powertools-python as a starting point, we can change to suit over time
- When users file issues, open feature requests, or submit PRs, they will now have a structured template that contains the information to help maintainers triage the request appropriately

chore: Add templates for filing issues and submitting pull requests

---

eksupdate/cli.py
eksupdate/src/boto_aws.py
eksupdate/src/eks_get_image_type.py
eksupdate/src/eksctlfinal.py
eksupdate/src/ekslogs.py
eksupdate/src/k8s_client.py
eksupdate/src/latest_ami.py
eksupdate/src/preflight_module.py
eksupdate/src/self_managed.py
eksupdate/starter.py
pyproject.toml

**Issue number:** #8 
Introduced pyproject.toml project configuration items specifically for accommodating autoformatting/styling with `black` and `isort`.
Codebase wasn't PEP-8 compliant, making contributions difficult.  Now, it's ✨

chore: Style codebase, add pyproject configs, and remove unused imports

---

poetry.lock
pyproject.toml

**Issue number:** N/A
This changes the `kubernetes` dependency pin from latest to between 21.0.0 - 24.x.x to ensure we use the latest revision within the major spec.
This change simply adjusts the installed dependencies as a part of package installation.

chore: Adjust the dependency pinning to ensure 24.x.x k8s spec is used

---

.gitignore
eksupgrade/cli.py
tests/test_cli.py

The goal of this PR is to modify the entry method to allow for easy passage of arguments to the parser method.  This ensures we can easily test the function.
Only visible change to end users includes the capability to run: `eksupgrade --version`

refactor: Adjust the entrypoint to accept arguments and add version flag

---

eksupgrade/src/S3Files/depricatedApi
eksupgrade/src/S3Files/version_dict.json
eksupgrade/src/k8s_client.py
eksupgrade/src/preflight_module.py
eksupgrade/starter.py

The goal of this PR is to update the standard workflow to:
- pull default version for a target upgrade from the EKS Add-on API and use that versus hardcoded version in version_dict.json` for everything except `cluster-autoscaler`.
- update `cluster-autoscaler` hardcoded version tags where relevant (and add missing entries for target versions).
- add method call to the update addon EKS API endpoint following manual pod recreation with new target version tags.
- Fix the workflow so it works for the enduser
The user now always pulls the default version from the EKS API for official add-ons.  This is then used to subsequently perform an HTTP request to initiate a formal EKS addon upgrade.
By submitting this pull request, I …

fix: Fix and update standard workflow to pull addon versions from EKS API

---

eksupgrade/src/boto_aws.py
eksupgrade/src/eksctlfinal.py
eksupgrade/src/k8s_client.py
eksupgrade/src/preflight_module.py
tests/test_k8s_client.py

Resolves https://github.com/aws-samples/amazon-eks-one-click-cluster-upgrade/issues/24
- Removed `region` argument from methods referenced in Issue #24.
- Updated arg name from `regionName` to `region` in eksctlfinal and k8s_client.
- Formatted eksctl commands to use fstrings consistently.
- Removed `v1` from `add_on_upgrade` since it is set inside the method.
- Removed taget assignment for the subprocess calls which used to be logged in a previous version.
**Note** : `loading_config` & `get_bearer_token` are redundant methods, but didn't change them in this PR to reduce the radius. 
No Changes
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …

fix: Remove unused args,  formatted eksctl commands

---

eksupgrade/cli.py

**Issue number:** #38
The goal of this PR is to eliminate the unnecessary, hardcoded region list used for outputting eligible regions in the help text.
No real change -- user will need to lookup eligible regions, but they should already know where a cluster resides (and it be valid, right?)

chore: Remove unused region list

---

.github/workflows/publish.yaml

**Issue number:** N/A
Add automatic build / publish to pypi / release on GH on tag actions.
Maintainer pushes tag to GH resulting in:
- Execution of `safety` CVE checks on dependencies (fail if CVEs are found)
- Compare the current git tag (that triggered the action) against the current python module version (fail if they don't match)
- Build python module and publish to PyPi
- Publish GitHub Release (attaching the build wheel and source tar.gz files and auto-generating the release notes from GH API).
**Disclaimer**: We value your time and bandwidth. As such, any pull requests …

ci: Add GitHub action to publish to PyPi and GH on tag

---

eksupgrade/src/k8s_client.py

**Issue number:** #42 
Fix bad `regionName` argument key usage against `loading_config` resulting in argumenterror.
Results in an operational workflow.

fix: Bad argument key passed to loading_config

---

eksupgrade/src/k8s_client.py

**Issue number:#51**
- Update the Eviction api used from `V1beta1Eviction` to `V1Eviction`
- This change in api is reference to the version pinned with the poetry lock we have on the repo. https://github.com/kubernetes-client/python/tree/v24.2.0/kubernetes/client/models
- https://github.com/aws-samples/eks-cluster-upgrade/blob/main/poetry.lock#L1086
This has been with two version upgrades : `1.21` -> `1.22` , `1.22`-> `1.23`
- Updated to handle both versions eventhough poetry lock is on 24.2.0
Fixes the issue#51 with the cluster upgrade when the utility attempts to drain nodes. …

fix: Update K8s eviction api from beta

---

.github/PULL_REQUEST_TEMPLATE.md

- Fix PR template to automatically link issues for closing on merge. If there is a `Resolves #xxx` or `Closes #xxx` within the template, GitHub will automatically link the issue to this PR and ensure its closed when merged
- Change PR template to ensure issues are automatically linked 
> Please share what the user experience looks like before and after this change

chore: Fix PR template to automatically link issues for closing on merge

---

eksupgrade/models/base.py
eksupgrade/models/eks.py
eksupgrade/src/eks_get_image_type.py
eksupgrade/src/k8s_client.py
tests/conftest.py
tests/test_k8s_client.py
tests/test_models_base.py
tests/test_models_eks.py
tests/test_utils.py

Resolves: #58 
Resolves: #33 
This change introduces the new submodule `models` including `models.eks` and `models.base`.  The `base` submodule includes base models relevant to creating reusable models specific to this tool and AWS services.
This provides a cleaner API for interacting with resources within the tool both from CLI and programmatically (enabling further automation using this tool and library in the future).

fix: Add eks and base data models

---

eksupgrade/__init__.py
eksupgrade/src/k8s_client.py
poetry.lock
pyproject.toml

Resolves: N/A
Remove unused variable that was previously erroneously casting string to int.
If cluster version split failed, this resulted in a failed execution in some workloads.  This variable is no longer used.

fix: Remove unused cluster version split value

---

eksupgrade/__init__.py
eksupgrade/src/preflight_module.py
poetry.lock
pyproject.toml

Resolves: #64 
Remove upper limit on cluster version (currently 1.24) and handle pod disruption budget leaving beta in the `1.25` kubernetes python client.
User will be prompted if version isn't within a minor release, but there is no longer any upper limit.  If a user requests to update against an ineligible version, it will fail.

fix: Remove cluster version upper limit and handle policy API release

---

eksupgrade/src/preflight_module.py

Resolves: #66
Updated the preflight check on gathering pod security policies for upgrade versions above 1.25. The updated Policy API has removed this attribute leading to failures on pre-flight checks.
Tested changes against running a pre-flight check and upgrading the cluster to `1.25`. 
No changes to user experience. This should continue to behave as expected for cluster upgrades till 1.25 and from 1.25.

fix: Updated checking psp only for versions below 1.25

---

eksupgrade/__init__.py
poetry.lock
pyproject.toml

Resolves: # N/A
> Reduce the current k8s python client pin to `">=21.0.0 <25.0.0"` to resolve incompatibility until a long term solution can be introduced.
> No change

fix: Adjust version to 0.6.1 and reduce k8s python client pin

---

eksupgrade/src/preflight_module.py

Resolves: #66 
Updated the import in pre-flight module to remove the collision of api names imported resulting in errors for attributes not present.
`from kubernetes.client import *` imports `PolicyV1Api` & `PolicyV1beta1Api`
Fixes the issue currently faced with version `0.5.1` onwards.

fix: Removed colliding apinames from import

---

.gitignore
eksupgrade/cli.py
eksupgrade/models/base.py
eksupgrade/models/eks.py
eksupgrade/src/boto_aws.py
eksupgrade/src/eks_get_image_type.py
eksupgrade/src/k8s_client.py
eksupgrade/src/latest_ami.py
eksupgrade/src/preflight_module.py
eksupgrade/src/self_managed.py
eksupgrade/starter.py
eksupgrade/utils.py

Changed the logging format to use timestamp and method line numbers to help with future debugging. Sample log lines below.
```
[INFO] : 2023-03-17 22:00:29 : botocore.credentials : Found credentials in environment variables.
[INFO] : 2023-03-17 22:00:30 : eksupgrade.src.preflight_module.91 : Cluster already upgraded to version 1.22
```
Resolves: #81 
- Added `get_logger` method  to utils
- Updated logger object to use the common `get_logger` utility
- Formatted the logs to use log level, date/time and module line numbers.
**Before**:
```
INFO:botocore.credentials:Found credentials in environment variables.
INFO:botocore.credentials:Found credentials in environment variables.
INFO:eksupgrade.src.preflight_module:Verifying User IAM Role....
INFO:eksupgrade.src.preflight_module:IAM role for …
```

feat: Logger format update

---

.github/workflows/e2e-test-template.yaml
README.md
eksupgrade/__main__.py
eksupgrade/cli.py
eksupgrade/models/base.py
eksupgrade/models/eks.py
eksupgrade/src/boto_aws.py
eksupgrade/src/eks_get_image_type.py
eksupgrade/src/k8s_client.py
eksupgrade/src/latest_ami.py
eksupgrade/src/preflight_module.py
eksupgrade/src/self_managed.py
eksupgrade/starter.py
eksupgrade/utils.py
poetry.lock
pyproject.toml
tests/test_cli.py

The goal of this PR is to swap out argparse with the more robust third-party module: `typer`, providing shell completion support, full `click` support, and much more.
Additionally, this PR enabled a confirmation prompt when executing eksupgrade following the pre-flight checks (requiring user input of y/N) and colorizes all outputs based on disposition of the operation originating the output.
Resolves: #31 
Swaps out the logger usage throughout most of the project with `typer.secho` pre-canned variants in `eksupgrade.utils@echo_*`, adds the `--interactive`/`--no-interactive` flags to disable prompts, and updates the entry script to use typer.
Colorized outputs based on status, shell completion support, clearer help text, and interactive/non-interactive workflows.
If your change doesn't …

fix: Modify entry logic to use Typer, colorize output, add interactive prompts

---

eksupgrade/src/eks_get_image_type.py
eksupgrade/src/preflight_module.py

Updated the eks image check and custom ami verification paths to not be locked against the owner-ids which were from `us-east-1`. The owner-id specified for windows amis were not matching the actuals owner ids.  This is an interim fix as described in #92 before rolling out  additional changes.
Errors noticed:
With the filtered values( including the owner-id) in describe images call, the ami ids were being flagged as custom amis.
```
Pod Security Policy with eks.privileged role exists.
Fetching node group details...
i-011a9369a6162bd0f cannot be upgraded as it uses a custom AMI!
```
Tested against a cluster with Windows node and based out of `us-east-2` to verify that both the windows nodes and the owner id mapping were not causing any regressions.
Resolves: #92 
Removed the owner id …

fix: Mismatch on Owner id for windows ami

---

eksupgrade/__init__.py
eksupgrade/src/eks_get_image_type.py
eksupgrade/src/preflight_module.py
pyproject.toml
tests/conftest.py
tests/test_eks_get_image_type.py

The goal of this PR is to resolve the `node_type` issue missing `windows` comparison for various distributions.
Resolves: #100
Modifies the node_type check to match on varying windows distributions versus explicitly `== windows`
Resolves failure to determine AMI.

fix: Adjust node_type check for get ami

---

eksupgrade/__init__.py
eksupgrade/src/preflight_module.py
eksupgrade/utils.py
pyproject.toml
tests/conftest.py
tests/test_utils.py

The goal of this PR is to add a deprecation notice to the pre/post-flight checks regarding the deprecation and changes from #103 
Resolves: NA
This PR adds test coverage for the remaining `utils.py` methods, adds the relevant deprecation notice to the pre/post-flight checks, and introduces the `echo_deprecation` method.
When using `0.8.3`, a user running `eksupgrade <cluster-name> <version> <region> --preflight` or `eksupgrade <cluster-name> <version> <region>` will receive a notice stating:
`{Pre|Post}-flight checks will be deprecated in the next minor release in favor of cluster summaries: #103`
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

test: Add pre/post-flight deprecation notice

---

.github/workflows/close-stale-issues.yaml

Adds a stale issue workflow with defined timelines to classify the  
Resolves: #118 
- Adds a stale issue workflow to review open issues .
- No impacts from the usage of eksupgrade
- Users with open issues will be scoped under this workflow.

feat: Added stale issue workflow

---

.github/workflows/e2e-test-template.yaml
.github/workflows/e2e-test.yaml

- Updating the workflow trigger to use deployment environment `dev`.
- Updated the cluster workflow to use a deployment environment `dev` than binding secrets to repository level.
No changes

fix: Workflow trigger bound to protected environment

---

.github/actions/dep-setup/action.yml

- Correct Poetry install script URL used in CI workflow
- Updates the URL where the Poetry install script is located
> Please share what the user experience looks like before and after this change

fix: Correct Poetry install script URL used in CI workflow
